language: node_js
node_js:
  - 4
  - 6
  - 8
before_install:
  - sudo apt-get -o Dpkg::Options::="--force-overwrite" install libzmq1
  - sudo apt-get -o Dpkg::Options::="--force-overwrite" install libzmq-dev
