language: node_js
node_js:
  - 0.10
  - 0.11
  - 0.12
  - iojs
before_install:
  - sudo apt-get -o Dpkg::Options::="--force-overwrite" install libzmq1
  - sudo apt-get -o Dpkg::Options::="--force-overwrite" install libzmq-dev